### ISSUE TITLE
Plugin not compatible with core v2?

### ISSUE THREAD

**Issue by esteban-turnocheck** [jaxon-php/jaxon-jquery#1]
Hi! I'm using jaxon-core v2, jaxon-dialogs, and now I'm trying to install this plugin, via composer, and getting 
`- jaxon-php/jaxon-jquery v1.0.0 requires jaxon-php/jaxon-core ~1.0 -> satisfiable by jaxon-php/jaxon-core[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.14, v1.0.15, v1.0.16, v1.0.17, v1.0.18, v1.0.19, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.0.x-dev] but these conflict with your requirements or minimum-stability.`

Is it something I'm doing wrong or this plugin doesn't work with jaxon-core v2?
Thanks!

**Comment by feuzeu** [comment]
Hi,
This plugin is now deprecated and its features are included in jaxon-core since version 2.
